# Generated by Django 2.0.3 on 2018-03-21 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20180320_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='creator_move',
            field=models.IntegerField(choices=[(1, 'rock'), (3, 'scissors'), (2, 'paper')], null=True),
        ),
        migrations.AlterField(
            model_name='round',
            name='opponent_move',
            field=models.IntegerField(choices=[(1, 'rock'), (3, 'scissors'), (2, 'paper')], null=True),
        ),
    ]
