# Generated by Django 2.0.3 on 2018-03-21 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_auto_20180321_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='creator_move',
            field=models.IntegerField(choices=[(2, 'paper'), (1, 'rock'), (3, 'scissors')], null=True),
        ),
        migrations.AlterField(
            model_name='round',
            name='opponent_move',
            field=models.IntegerField(choices=[(2, 'paper'), (1, 'rock'), (3, 'scissors')], null=True),
        ),
    ]
