# Generated by Django 2.0.3 on 2018-03-21 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_auto_20180321_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='creator_move',
            field=models.IntegerField(blank=True, choices=[(3, 'scissors'), (2, 'paper'), (1, 'rock')], null=True),
        ),
        migrations.AlterField(
            model_name='round',
            name='opponent_move',
            field=models.IntegerField(blank=True, choices=[(3, 'scissors'), (2, 'paper'), (1, 'rock')], null=True),
        ),
    ]
